CREATE TABLE users
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                VARCHAR(255)                            NOT NULL,
    password                VARCHAR(255)                            NOT NULL,
    email                   VARCHAR(255)                            NOT NULL,
    account_non_expired     BOOLEAN                                 NOT NULL,
    account_non_locked      BOOLEAN                                 NOT NULL,
    credentials_non_expired BOOLEAN                                 NOT NULL,
    enabled                 BOOLEAN                                 NOT NULL,
    lock_time               TIMESTAMP WITHOUT TIME ZONE,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    update_at               TIMESTAMP WITHOUT TIME ZONE,
    failed_attempts         INTEGER,
    last_login              TIMESTAMP WITHOUT TIME ZONE,
    locked_until            TIMESTAMP WITHOUT TIME ZONE,
    role                    VARCHAR(255)                            NOT NULL,
    roles                   SMALLINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);
CREATE TABLE users
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                VARCHAR(255)                            NOT NULL,
    password                VARCHAR(255)                            NOT NULL,
    email                   VARCHAR(255)                            NOT NULL,
    account_non_expired     BOOLEAN                                 NOT NULL,
    account_non_locked      BOOLEAN                                 NOT NULL,
    credentials_non_expired BOOLEAN                                 NOT NULL,
    enabled                 BOOLEAN                                 NOT NULL,
    lock_time               TIMESTAMP WITHOUT TIME ZONE,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    update_at               TIMESTAMP WITHOUT TIME ZONE,
    failed_attempts         INTEGER,
    last_login              TIMESTAMP WITHOUT TIME ZONE,
    locked_until            TIMESTAMP WITHOUT TIME ZONE,
    role                    VARCHAR(255)                            NOT NULL,
    roles                   SMALLINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);